-- ============================================================================
-- UNITED RENTALS DEMO - Load Data: Stage + COPY INTO
-- ============================================================================
--
-- Loads generated CSV data from internal stage into RAW tables.
-- Uses INFER_SCHEMA for dynamic column detection and MATCH_BY_COLUMN_NAME
-- for resilient loading (same pattern as core DCA 04_load_data.sql).
--
-- Prerequisites: Run 01_ur_setup.sql first, upload CSVs to stage.
-- RUN AS: DATA_ADMIN
-- ============================================================================

USE ROLE DATA_ADMIN;
USE DATABASE RAW_DEV;
USE SCHEMA RAW_DEV.UNITED_RENTALS;
USE WAREHOUSE INGEST_WH;

-- ═══════════════════════════════════════════════════════════════════════════
-- INTERNAL STAGE
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE STAGE RAW_DEV.UNITED_RENTALS.UR_DATA_STAGE
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'United Rentals demo data files';

-- Upload CSVs: PUT file:///path/to/demos/united-rentals/data/*.csv @UR_DATA_STAGE;

-- ═══════════════════════════════════════════════════════════════════════════
-- FILE FORMAT
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE FILE FORMAT RAW_DEV.UNITED_RENTALS.UR_CSV_FORMAT
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    COMMENT = 'CSV format for UR data files';

-- ═══════════════════════════════════════════════════════════════════════════
-- RAW TABLES (explicit DDL for clarity and governance tagging)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE OR REPLACE TABLE RAW_DEV.UNITED_RENTALS.BRANCHES (
    BRANCH_ID VARCHAR(10),
    BRANCH_NAME VARCHAR(200),
    BRANCH_TYPE VARCHAR(50),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(100),
    STATE VARCHAR(5),
    ZIP_CODE VARCHAR(10),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    REGION VARCHAR(20),
    DISTRICT VARCHAR(20),
    PHONE VARCHAR(30),
    MANAGER_NAME VARCHAR(100),
    OPEN_DATE DATE,
    EMPLOYEE_COUNT NUMBER,
    IS_ACTIVE BOOLEAN,
    _SOURCE_TABLE VARCHAR(50),
    _ROW_HASH VARCHAR(64),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(50),
    _IS_CURRENT BOOLEAN,
    _VALID_FROM TIMESTAMP_NTZ,
    _VALID_TO TIMESTAMP_NTZ
)
COMMENT = 'United Rentals branch/yard locations with geospatial coordinates';

CREATE OR REPLACE TABLE RAW_DEV.UNITED_RENTALS.EQUIPMENT (
    EQUIPMENT_ID VARCHAR(12),
    SERIAL_NUMBER VARCHAR(20),
    MAKE VARCHAR(50),
    MODEL VARCHAR(50),
    CATEGORY VARCHAR(30),
    SUBCATEGORY VARCHAR(50),
    DESCRIPTION VARCHAR(200),
    YEAR_MANUFACTURED NUMBER,
    ACQUISITION_DATE DATE,
    ACQUISITION_COST FLOAT,
    REPLACEMENT_COST FLOAT,
    BRANCH_ID VARCHAR(10),
    STATUS VARCHAR(20),
    CONDITION VARCHAR(20),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    LAST_SERVICE_DATE DATE,
    NEXT_SERVICE_DUE DATE,
    HOUR_METER_READING NUMBER,
    DAILY_RATE FLOAT,
    WEEKLY_RATE FLOAT,
    MONTHLY_RATE FLOAT,
    _SOURCE_TABLE VARCHAR(50),
    _ROW_HASH VARCHAR(64),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(50),
    _IS_CURRENT BOOLEAN,
    _VALID_FROM TIMESTAMP_NTZ,
    _VALID_TO TIMESTAMP_NTZ
)
COMMENT = 'United Rentals fleet assets with location and pricing';

CREATE OR REPLACE TABLE RAW_DEV.UNITED_RENTALS.CUSTOMERS (
    CUSTOMER_ID VARCHAR(12),
    COMPANY_NAME VARCHAR(200),
    CONTACT_FIRST_NAME VARCHAR(50),
    CONTACT_LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PHONE VARCHAR(30),
    ADDRESS VARCHAR(200),
    CITY VARCHAR(100),
    STATE VARCHAR(5),
    ZIP_CODE VARCHAR(10),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    CUSTOMER_TYPE VARCHAR(30),
    CREDIT_RATING VARCHAR(5),
    ACCOUNT_STATUS VARCHAR(20),
    CREDIT_LIMIT FLOAT,
    YTD_REVENUE FLOAT,
    _SOURCE_TABLE VARCHAR(50),
    _ROW_HASH VARCHAR(64),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(50),
    _IS_CURRENT BOOLEAN,
    _VALID_FROM TIMESTAMP_NTZ,
    _VALID_TO TIMESTAMP_NTZ
)
COMMENT = 'United Rentals customer accounts';

CREATE OR REPLACE TABLE RAW_DEV.UNITED_RENTALS.RENTAL_CONTRACTS (
    CONTRACT_ID VARCHAR(12),
    CUSTOMER_ID VARCHAR(12),
    EQUIPMENT_ID VARCHAR(12),
    BRANCH_ID VARCHAR(10),
    RENTAL_START_DATE DATE,
    RENTAL_END_DATE DATE,
    DURATION_DAYS NUMBER,
    DAILY_RATE FLOAT,
    WEEKLY_RATE FLOAT,
    MONTHLY_RATE FLOAT,
    TOTAL_AMOUNT FLOAT,
    STATUS VARCHAR(20),
    DELIVERY_ADDRESS VARCHAR(200),
    DELIVERY_CITY VARCHAR(100),
    DELIVERY_STATE VARCHAR(5),
    DELIVERY_LATITUDE FLOAT,
    DELIVERY_LONGITUDE FLOAT,
    PO_NUMBER VARCHAR(20),
    SALES_REP VARCHAR(100),
    _SOURCE_TABLE VARCHAR(50),
    _ROW_HASH VARCHAR(64),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(50),
    _IS_CURRENT BOOLEAN,
    _VALID_FROM TIMESTAMP_NTZ,
    _VALID_TO TIMESTAMP_NTZ
)
COMMENT = 'United Rentals rental transactions';

CREATE OR REPLACE TABLE RAW_DEV.UNITED_RENTALS.MAINTENANCE_RECORDS (
    RECORD_ID VARCHAR(12),
    EQUIPMENT_ID VARCHAR(12),
    BRANCH_ID VARCHAR(10),
    MAINTENANCE_TYPE VARCHAR(20),
    DESCRIPTION VARCHAR(500),
    SCHEDULED_DATE DATE,
    START_DATE DATE,
    COMPLETION_DATE DATE,
    LABOR_HOURS FLOAT,
    PARTS_COST FLOAT,
    LABOR_COST FLOAT,
    TOTAL_COST FLOAT,
    TECHNICIAN_NAME VARCHAR(100),
    STATUS VARCHAR(20),
    _SOURCE_TABLE VARCHAR(50),
    _ROW_HASH VARCHAR(64),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(50),
    _IS_CURRENT BOOLEAN,
    _VALID_FROM TIMESTAMP_NTZ,
    _VALID_TO TIMESTAMP_NTZ
)
COMMENT = 'United Rentals equipment maintenance and service events';

CREATE OR REPLACE TABLE RAW_DEV.UNITED_RENTALS.TELEMATICS (
    READING_ID VARCHAR(15),
    EQUIPMENT_ID VARCHAR(12),
    READING_TIMESTAMP TIMESTAMP_NTZ,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    ENGINE_HOURS FLOAT,
    FUEL_LEVEL_PCT FLOAT,
    BATTERY_VOLTAGE FLOAT,
    IS_RUNNING BOOLEAN,
    SPEED_MPH FLOAT,
    AMBIENT_TEMP_F FLOAT,
    FAULT_CODE VARCHAR(10),
    FAULT_DESCRIPTION VARCHAR(200),
    _SOURCE_TABLE VARCHAR(50),
    _ROW_HASH VARCHAR(64),
    _LOADED_AT TIMESTAMP_NTZ,
    _SOURCE_SYSTEM VARCHAR(50),
    _IS_CURRENT BOOLEAN,
    _VALID_FROM TIMESTAMP_NTZ,
    _VALID_TO TIMESTAMP_NTZ
)
COMMENT = 'United Rentals IoT/GPS telematics readings';

-- ═══════════════════════════════════════════════════════════════════════════
-- COPY INTO (load from stage)
-- ═══════════════════════════════════════════════════════════════════════════

COPY INTO RAW_DEV.UNITED_RENTALS.BRANCHES
    FROM @RAW_DEV.UNITED_RENTALS.UR_DATA_STAGE/branches.csv
    FILE_FORMAT = RAW_DEV.UNITED_RENTALS.UR_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

COPY INTO RAW_DEV.UNITED_RENTALS.EQUIPMENT
    FROM @RAW_DEV.UNITED_RENTALS.UR_DATA_STAGE/equipment.csv
    FILE_FORMAT = RAW_DEV.UNITED_RENTALS.UR_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

COPY INTO RAW_DEV.UNITED_RENTALS.CUSTOMERS
    FROM @RAW_DEV.UNITED_RENTALS.UR_DATA_STAGE/customers.csv
    FILE_FORMAT = RAW_DEV.UNITED_RENTALS.UR_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

COPY INTO RAW_DEV.UNITED_RENTALS.RENTAL_CONTRACTS
    FROM @RAW_DEV.UNITED_RENTALS.UR_DATA_STAGE/rental_contracts.csv
    FILE_FORMAT = RAW_DEV.UNITED_RENTALS.UR_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

COPY INTO RAW_DEV.UNITED_RENTALS.MAINTENANCE_RECORDS
    FROM @RAW_DEV.UNITED_RENTALS.UR_DATA_STAGE/maintenance_records.csv
    FILE_FORMAT = RAW_DEV.UNITED_RENTALS.UR_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

COPY INTO RAW_DEV.UNITED_RENTALS.TELEMATICS
    FROM @RAW_DEV.UNITED_RENTALS.UR_DATA_STAGE/telematics.csv
    FILE_FORMAT = RAW_DEV.UNITED_RENTALS.UR_CSV_FORMAT
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
    ON_ERROR = 'CONTINUE';

-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFY LOAD
-- ═══════════════════════════════════════════════════════════════════════════

SELECT 'BRANCHES' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW_DEV.UNITED_RENTALS.BRANCHES
UNION ALL SELECT 'EQUIPMENT', COUNT(*) FROM RAW_DEV.UNITED_RENTALS.EQUIPMENT
UNION ALL SELECT 'CUSTOMERS', COUNT(*) FROM RAW_DEV.UNITED_RENTALS.CUSTOMERS
UNION ALL SELECT 'RENTAL_CONTRACTS', COUNT(*) FROM RAW_DEV.UNITED_RENTALS.RENTAL_CONTRACTS
UNION ALL SELECT 'MAINTENANCE_RECORDS', COUNT(*) FROM RAW_DEV.UNITED_RENTALS.MAINTENANCE_RECORDS
UNION ALL SELECT 'TELEMATICS', COUNT(*) FROM RAW_DEV.UNITED_RENTALS.TELEMATICS
ORDER BY TABLE_NAME;
