-- ============================================================================
-- SUTTER HEALTH DEMO — Load Data: Stage + COPY INTO
-- ============================================================================
--
-- Creates an internal stage and loads all 5 CSV files generated by
-- tools/generate_sh_claims_data.py into the raw tables.
--
-- Stage path convention:
--   @RAW_DEV.STAGING.DATA_STAGE/sutter_health/raw_claims.csv
--   @RAW_DEV.STAGING.DATA_STAGE/sutter_health/member_enrollment.csv
--   @RAW_DEV.STAGING.DATA_STAGE/sutter_health/provider_directory.csv
--   @RAW_DEV.STAGING.DATA_STAGE/sutter_health/risk_adjustment_flags.csv
--   @RAW_DEV.STAGING.DATA_STAGE/sutter_health/claims_summary.csv
--
-- PUT commands (run from tools/ directory after generating data):
--   PUT file://../data/raw_claims.csv @RAW_DEV.STAGING.DATA_STAGE/sutter_health/ AUTO_COMPRESS=TRUE;
--   PUT file://../data/member_enrollment.csv @RAW_DEV.STAGING.DATA_STAGE/sutter_health/ AUTO_COMPRESS=TRUE;
--   PUT file://../data/provider_directory.csv @RAW_DEV.STAGING.DATA_STAGE/sutter_health/ AUTO_COMPRESS=TRUE;
--   PUT file://../data/risk_adjustment_flags.csv @RAW_DEV.STAGING.DATA_STAGE/sutter_health/ AUTO_COMPRESS=TRUE;
--   PUT file://../data/claims_summary.csv @RAW_DEV.STAGING.DATA_STAGE/sutter_health/ AUTO_COMPRESS=TRUE;
--
-- Prerequisites: 02_sh_claims_model.sql and CSV files uploaded to stage
-- RUN AS: DATA_ADMIN
-- ============================================================================

USE ROLE DATA_ADMIN;
USE DATABASE RAW_DEV;
USE SCHEMA SUTTER_HEALTH;
USE WAREHOUSE INGEST_WH;

-- ═══════════════════════════════════════════════════════════════════════════
-- Ensure stage exists (created by core DCA sql/03_raw_layer.sql)
-- ═══════════════════════════════════════════════════════════════════════════

CREATE STAGE IF NOT EXISTS RAW_DEV.STAGING.DATA_STAGE
    COMMENT = 'DCA shared internal stage for CSV uploads'
    DIRECTORY = (ENABLE = TRUE);

-- CSV file format (re-usable)
CREATE FILE FORMAT IF NOT EXISTS RAW_DEV.STAGING.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    DATE_FORMAT = 'YYYY-MM-DD'
    TIMESTAMP_FORMAT = 'YYYY-MM-DD HH24:MI:SS'
    COMMENT = 'Standard CSV format for DCA data loads';

-- ═══════════════════════════════════════════════════════════════════════════
-- COPY INTO — raw_claims
-- ═══════════════════════════════════════════════════════════════════════════

COPY INTO RAW_DEV.SUTTER_HEALTH.RAW_CLAIMS (
    CLAIM_ID, CLAIM_LINE_NUMBER, MEMBER_ID, PROVIDER_NPI,
    CLAIM_TYPE, CLAIM_SUBTYPE, BILL_TYPE_CODE, PLACE_OF_SERVICE_CODE, PLACE_OF_SERVICE_DESC,
    PRIMARY_DX_CODE, SECONDARY_DX_CODE_1, SECONDARY_DX_CODE_2,
    PROCEDURE_CODE, PROCEDURE_MODIFIER, REVENUE_CODE, DRG_CODE,
    BILLED_AMOUNT, ALLOWED_AMOUNT, PAID_AMOUNT, MEMBER_RESPONSIBILITY,
    COINSURANCE_AMOUNT, COPAY_AMOUNT, DEDUCTIBLE_AMOUNT,
    CLAIM_STATUS, DENIAL_REASON_CODE, DENIAL_REASON_DESC, PAYER_CLAIM_CONTROL_NUM,
    SERVICE_DATE, SERVICE_DATE_END, CLAIM_SUBMISSION_DATE, ADJUDICATION_DATE, PLAN_YEAR,
    CLAIM_RECEIVED_TS, CLAIM_PROCESSED_TS, SLA_TARGET_HOURS, SLA_MET, SLA_BREACH_HOURS, PROCESSING_HOURS,
    NETWORK_STATUS, PRIOR_AUTH_NUMBER, REFERRAL_NUMBER,
    _SOURCE_SYSTEM, _LOADED_AT, _RECORD_HASH
)
FROM @RAW_DEV.STAGING.DATA_STAGE/sutter_health/raw_claims
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = CONTINUE
PURGE = FALSE;

-- ═══════════════════════════════════════════════════════════════════════════
-- COPY INTO — member_enrollment
-- ═══════════════════════════════════════════════════════════════════════════

COPY INTO RAW_DEV.SUTTER_HEALTH.MEMBER_ENROLLMENT (
    MEMBER_ID, SUBSCRIBER_ID, MBI_NUMBER, MEDICAID_ID, MEMBER_RELATIONSHIP,
    PLAN_ID, PLAN_NAME, PLAN_TYPE, PRODUCT_LINE, GROUP_NUMBER, EMPLOYER_NAME,
    DATE_OF_BIRTH, GENDER, ZIP_CODE, COUNTY_CODE, STATE_CODE,
    COVERAGE_START_DATE, COVERAGE_END_DATE, ENROLLMENT_STATUS,
    COBRA_FLAG, DUAL_ELIGIBLE, LIS_LEVEL,
    RISK_SCORE, PRIOR_YEAR_RISK_SCORE, RISK_CATEGORY, RISK_PERCENTILE, PROSPECTIVE_RISK_SCORE,
    CARE_MANAGEMENT_FLAG, CHRONIC_CONDITION_COUNT, PRIMARY_CARE_NPI,
    _SOURCE_SYSTEM, _VALID_FROM, _VALID_TO, _IS_CURRENT, _LOADED_AT, _RECORD_HASH
)
FROM @RAW_DEV.STAGING.DATA_STAGE/sutter_health/member_enrollment
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = CONTINUE
PURGE = FALSE;

-- ═══════════════════════════════════════════════════════════════════════════
-- COPY INTO — provider_directory
-- ═══════════════════════════════════════════════════════════════════════════

COPY INTO RAW_DEV.SUTTER_HEALTH.PROVIDER_DIRECTORY (
    PROVIDER_NPI, GROUP_NPI, TIN, PROVIDER_LAST_NAME, PROVIDER_FIRST_NAME, PROVIDER_CREDENTIAL,
    SPECIALTY_CODE, SPECIALTY_DESC, TAXONOMY_CODE, PRIMARY_CARE_FLAG,
    NETWORK_STATUS, NETWORK_EFFECTIVE_DATE, NETWORK_TERM_DATE,
    ACCEPTING_NEW_PATIENTS, TELEHEALTH_ENABLED, QUALITY_TIER,
    PRACTICE_ADDRESS_LINE1, PRACTICE_CITY, PRACTICE_STATE, PRACTICE_ZIP, PRACTICE_COUNTY_CODE,
    PRACTICE_LATITUDE, PRACTICE_LONGITUDE, PRACTICE_PHONE,
    CREDENTIAL_STATUS, CREDENTIAL_EXPIRY_DATE, BOARD_CERTIFIED, MALPRACTICE_FLAG,
    CLAIM_VOLUME_30D, RISK_FLAG_VOLUME_30D, AVG_RISK_SCORE_PANEL,
    _SOURCE_SYSTEM, _LOADED_AT, _RECORD_HASH
)
FROM @RAW_DEV.STAGING.DATA_STAGE/sutter_health/provider_directory
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = CONTINUE
PURGE = FALSE;

-- ═══════════════════════════════════════════════════════════════════════════
-- COPY INTO — risk_adjustment_flags (seed/historical)
-- ═══════════════════════════════════════════════════════════════════════════

COPY INTO RAW_DEV.SUTTER_HEALTH.RISK_ADJUSTMENT_FLAGS (
    FLAG_ID, MEMBER_ID, CLAIM_ID,
    HCC_CODE, HCC_DESCRIPTION, ICD10_CODE, ICD10_DESCRIPTION,
    RISK_WEIGHT, RISK_COEFFICIENT, INCREMENTAL_RISK,
    FLAG_DATE, FLAG_SOURCE, FLAG_STATUS, VALIDATION_SOURCE, PLAN_YEAR,
    CLAIM_SLA_MET, CLAIM_PROCESSING_HOURS, PIPELINE_RUN_ID, RUN_DATE,
    _SOURCE_SYSTEM, _LOADED_AT
)
FROM @RAW_DEV.STAGING.DATA_STAGE/sutter_health/risk_adjustment_flags
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = CONTINUE
PURGE = FALSE;

-- ═══════════════════════════════════════════════════════════════════════════
-- COPY INTO — claims_summary
-- ═══════════════════════════════════════════════════════════════════════════

COPY INTO RAW_DEV.SUTTER_HEALTH.CLAIMS_SUMMARY (
    SUMMARY_ID, MEMBER_ID, PLAN_YEAR,
    TOTAL_CLAIMS, PAID_CLAIMS, DENIED_CLAIMS, PENDING_CLAIMS,
    UNIQUE_PROVIDERS, UNIQUE_CLAIM_TYPES,
    TOTAL_BILLED_AMOUNT, TOTAL_ALLOWED_AMOUNT, TOTAL_PAID_AMOUNT, TOTAL_MEMBER_RESP,
    DENIAL_RATE,
    SLA_BREACH_COUNT, SLA_MET_COUNT, SLA_BREACH_RATE,
    AVG_PROCESSING_HOURS, MAX_PROCESSING_HOURS, P90_PROCESSING_HOURS,
    RISK_SCORE, PRIMARY_RISK_CATEGORY, ACTIVE_HCC_COUNT, CHRONIC_CONDITION_COUNT,
    FIRST_SERVICE_DATE, LAST_SERVICE_DATE, LAST_UPDATED_TS,
    _SOURCE_SYSTEM, _LOADED_AT
)
FROM @RAW_DEV.STAGING.DATA_STAGE/sutter_health/claims_summary
FILE_FORMAT = (FORMAT_NAME = 'RAW_DEV.STAGING.CSV_FORMAT')
ON_ERROR = CONTINUE
PURGE = FALSE;

-- ═══════════════════════════════════════════════════════════════════════════
-- Validation counts
-- ═══════════════════════════════════════════════════════════════════════════

SELECT 'RAW_CLAIMS'           AS table_name, COUNT(*) AS row_count FROM RAW_DEV.SUTTER_HEALTH.RAW_CLAIMS UNION ALL
SELECT 'MEMBER_ENROLLMENT'    AS table_name, COUNT(*) AS row_count FROM RAW_DEV.SUTTER_HEALTH.MEMBER_ENROLLMENT UNION ALL
SELECT 'PROVIDER_DIRECTORY'   AS table_name, COUNT(*) AS row_count FROM RAW_DEV.SUTTER_HEALTH.PROVIDER_DIRECTORY UNION ALL
SELECT 'RISK_ADJUSTMENT_FLAGS' AS table_name, COUNT(*) AS row_count FROM RAW_DEV.SUTTER_HEALTH.RISK_ADJUSTMENT_FLAGS UNION ALL
SELECT 'CLAIMS_SUMMARY'       AS table_name, COUNT(*) AS row_count FROM RAW_DEV.SUTTER_HEALTH.CLAIMS_SUMMARY
ORDER BY table_name;
